### ISSUE TITLE
http url not working

### ISSUE THREAD

**Issue by evelinprissy1** [sticksen/STKWebKitViewController#17]
its working fine only with "https". not working in "http".

**Comment by noelhunter** [comment]
You need to add an app transport security policy if you need http

<key>NSAppTransportSecurity</key>
    <dict>
        
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>

See [http://stackoverflow.com/questions/31065204/ios-9-are-webviews-exempt-from-the-app-transport-security-exceptions-ats](url)

**Comment by sticksen** [comment]
I guess this is no issue here, so I´m closing it. Thanks!
